### PR TITLE
feat: add python 3.8 support

### PR DESCRIPTION
**Pull request by nathanielheitsch**
Changed python constraints to allow 3.9, added unit tests 

## Description
<!--- 
Describe your changes in detail 
-->

## Motivation and Context
I have projects stuck on 3.9 and this project was compatible out of the box it just needed the version constraint changed.

## How Has This Been Tested?
Unit tests have been added and run.

```
==================================================================================================================================== test session starts ====================================================================================================================================
platform darwin -- Python 3.9.18, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/nathanielheitsch/projects/poetry-stickywheel-plugin
configfile: pyproject.toml
collected 9 items                                                                                                                                                                                                                                                                           

tests/test_poetry_stickywheel_plugin.py .........                                                                                                                                                                                                                                     [100%]

===================================================================================================================================== 9 passed in 0.26s =====================================================================================================================================
Name                               Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------------
src/poetry_stickywheel_plugin.py      60     11     18      2    78%   80, 85, 98-111
------------------------------------------------------------------------------
TOTAL                                 60     11     18      2    78%
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING.md** document.
- [ x] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by nathanielheitsch** [comment]
@danielknell Is this something you are willing to merge in?

**Comment by danielknell** [comment]
sorry, it's been chaotic recently and I missed this.

I will need to review properly but on principal its a welcome change, I will try and find some time this week to look over it.

**Comment by nathanielheitsch** [comment]
Cool thank you!

**Comment by nathanielheitsch** [comment]
Sure thing, its updated now, thanks!

**Review by danielknell — APPROVED** [review]

**Comment by nathanielheitsch** [comment]
Yep, python 3.8 is working for me

**Comment by danielknell** [comment]
released as [v0.2.0 ](https://github.com/artisanofcode/poetry-stickywheel-plugin/releases/tag/v0.2.0)

**Pull request merged**
